services:
  elective_formatter_bundle.response.formatter:
    class: Elective\FormatterBundle\Response\Formatter
      arguments:
        $requestStack: '@request_stack'
        $parsers: { application/json: '@elective_formatter_bundle.parsers.json' }
        $cache: '@Symfony\Component\Cache\Adapter\TagAwareAdapter'
      calls:
        - [ 'setHeaders', ['%elective_formatter.response.formatter.headers%']]

  Elective\FormatterBundle\Response\FormatterInterface: '@elective_formatter_bundle.response.formatter'

  elective_formatter_bundle.request.handler:
    class: Elective\FormatterBundle\Request\Handler
    arguments:
      $requestStack: '@request_stack'

  Elective\FormatterBundle\Request\HandlerInterface: '@elective_formatter_bundle.request.handler'

  elective_formatter_bundle.parsers.json: 
    class: Elective\FormatterBundle\Parsers\Json
